<a href="https://colab.research.google.com/github/VictorHugoTesti/-am-t4-s1a2026/blob/main/neuroalgoritmos_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importar Dados Drive

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Bibliotecas Puyhon

In [2]:
!pip -q install plotly
!pip -q install yellowbrick

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
import pickle
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Impartando Digest base_ibama

In [5]:
with open ('/content/drive/MyDrive/Aprendizagem de Maquina/ibama.pkl', 'rb') as f:
  X_treinamento, Y_treinamento, X_teste, Y_teste = pickle.load(f)

In [6]:
X_treinamento.shape, Y_treinamento.shape

((2479, 261), (2479,))

In [7]:
X_teste.shape, Y_teste.shape

((438, 261), (438,))

# Pipeline Árvore de Decisão | Treemap [Fase 1 - base_ibama]

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
arvore_ibama = DecisionTreeClassifier(criterion='entropy', random_state=0)
arvore_ibama.fit(X_treinamento, Y_treinamento)
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_samples_leaf=1, min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=0, splitter='best')

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [10]:
arvore_previsoes = arvore_ibama.predict(X_teste)
arvore_previsoes

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,

In [11]:
print("Acurácia:", accuracy_score(Y_teste, arvore_previsoes))
print("\nMatrix de Confusão:\n", confusion_matrix(Y_teste, arvore_previsoes))
print("\nRelatório Final:\n", classification_report(Y_teste, arvore_previsoes))

Acurácia: 0.6963470319634704

Matrix de Confusão:
 [[199  34]
 [ 99 106]]

Relatório Final:
               precision    recall  f1-score   support

           0       0.67      0.85      0.75       233
           1       0.76      0.52      0.61       205

    accuracy                           0.70       438
   macro avg       0.71      0.69      0.68       438
weighted avg       0.71      0.70      0.69       438



# Pipeline Random Forest | Digest Pickle [Fase 2 - base_ibama]

In [12]:
from sklearn.ensemble import RandomForestClassifier
from warnings import warn

In [13]:
random_ibama = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
random_ibama.fit(X_treinamento, Y_treinamento)
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth='auto',
                       min_impurity_decrease=0.0, min_samples_split=None,
                       min_samples_leaf=1, min_weight_fraction_leaf=0.0,
                       n_estimators=10, n_jobs=None, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)

RandomForestClassifier(criterion='entropy', max_depth='auto',
                       min_samples_split=None, n_estimators=10, random_state=0)

In [14]:
random_previsores = random_ibama.predict(X_teste)
random_previsores

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,

In [15]:
print("Acurácia:", accuracy_score(Y_teste, random_previsores))
print("\nMatrix de Confusão:\n", confusion_matrix(Y_teste, random_previsores))
print("\nRelatório Final:\n", classification_report(Y_teste, random_previsores))

Acurácia: 0.7009132420091324

Matrix de Confusão:
 [[191  42]
 [ 89 116]]

Relatório Final:
               precision    recall  f1-score   support

           0       0.68      0.82      0.74       233
           1       0.73      0.57      0.64       205

    accuracy                           0.70       438
   macro avg       0.71      0.69      0.69       438
weighted avg       0.71      0.70      0.70       438



# Pipeline SVM | Digest [Fase 3 - base_ibama]

In [16]:
from sklearn.svm import SVC

In [17]:
svm_ibama = SVC(kernel='rbf', random_state=1, C=2.0)
svm_ibama.fit(X_treinamento, Y_treinamento)
SVC(C=2.0, break_ties=False, cache_size=200, class_weight=None,
    coef0=0.0, decision_function_shape='ovr', degree=3,
    kernel='rbf', max_iter=1, probability=False, random_state=1,
    shrinking=True, tol=0.001, verbose=False)

SVC(C=2.0, max_iter=1, random_state=1)

In [18]:
svm_previsores = svm_ibama.predict(X_teste)
svm_previsores

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,

In [19]:
print("Acurácia:", accuracy_score(Y_teste, svm_previsores))
print("\nMatrix de Confusão:\n", confusion_matrix(Y_teste, svm_previsores))
print("\nRelatório Final:\n", classification_report(Y_teste, svm_previsores))

Acurácia: 0.7123287671232876

Matrix de Confusão:
 [[212  21]
 [105 100]]

Relatório Final:
               precision    recall  f1-score   support

           0       0.67      0.91      0.77       233
           1       0.83      0.49      0.61       205

    accuracy                           0.71       438
   macro avg       0.75      0.70      0.69       438
weighted avg       0.74      0.71      0.70       438



# Pipeline Redes Neurais | Digest [Fase 4 - base_ibama]

In [20]:
from sklearn.neural_network import MLPClassifier

In [21]:
redeneural_ibama = MLPClassifier(verbose=True, max_iter=1000,
                                 tol=0.000010, solver='adam',
                                 hidden_layer_sizes=(100), activation='relu')
redeneural_ibama.fit(X_treinamento, Y_treinamento)

Iteration 1, loss = 0.72052232
Iteration 2, loss = 0.58541915
Iteration 3, loss = 0.52785804
Iteration 4, loss = 0.49685948
Iteration 5, loss = 0.48040745
Iteration 6, loss = 0.46968895
Iteration 7, loss = 0.46162579
Iteration 8, loss = 0.45596269
Iteration 9, loss = 0.45038089
Iteration 10, loss = 0.44681191
Iteration 11, loss = 0.44386384
Iteration 12, loss = 0.44024141
Iteration 13, loss = 0.43720125
Iteration 14, loss = 0.43502754
Iteration 15, loss = 0.43303010
Iteration 16, loss = 0.43004760
Iteration 17, loss = 0.42809037
Iteration 18, loss = 0.42620338
Iteration 19, loss = 0.42525313
Iteration 20, loss = 0.42295492
Iteration 21, loss = 0.42050638
Iteration 22, loss = 0.41937097
Iteration 23, loss = 0.41802026
Iteration 24, loss = 0.41611613
Iteration 25, loss = 0.41472050
Iteration 26, loss = 0.41351830
Iteration 27, loss = 0.41150126
Iteration 28, loss = 0.41197784
Iteration 29, loss = 0.40964454
Iteration 30, loss = 0.40811149
Iteration 31, loss = 0.40711297
Iteration 32, los

MLPClassifier(hidden_layer_sizes=100, max_iter=1000, tol=1e-05, verbose=True)

In [22]:
redeneural_ibama.out_activation_

'logistic'

In [23]:
redeneureal_previsoes = redeneural_ibama.predict(X_teste)
redeneureal_previsoes

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,

In [24]:
print("Acurácia:", accuracy_score(Y_teste, redeneureal_previsoes))
print("\nMatrix de Confusão:\n", confusion_matrix(Y_teste, redeneureal_previsoes))
print("\nRelatório Final:\n", classification_report(Y_teste, redeneureal_previsoes))

Acurácia: 0.6894977168949772

Matrix de Confusão:
 [[193  40]
 [ 96 109]]

Relatório Final:
               precision    recall  f1-score   support

           0       0.67      0.83      0.74       233
           1       0.73      0.53      0.62       205

    accuracy                           0.69       438
   macro avg       0.70      0.68      0.68       438
weighted avg       0.70      0.69      0.68       438



# Pipeline Preparação de Dados (KNN) | Digest [Fase 5 - base_ibama]

In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [26]:
parametros = {'n_neighbors': [3, 5, 10, 20],
              'p': [1,2]}

In [27]:
grid_ibama = GridSearchCV(estimator=KNeighborsClassifier(), param_grid=parametros)
grid_ibama.fit(X_treinamento, Y_treinamento)
melhor_parametro_ibama = grid_ibama.best_params_
melhor_resultado_ibama = grid_ibama.best_score_

In [28]:
print(melhor_parametro_ibama)
print(melhor_resultado_ibama)

{'n_neighbors': 5, 'p': 1}
0.7075358422939069
